
package javax.swing;
import java.awt.Color;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
public class v1 extends javax.swing.JFrame {
Connection conn=null;
ResultSet RS=null;
PreparedStatement PST=null;
Statement stmt = null;

    
    public v1() {
        initComponents();
       
        conn=MysqlConnect.ConnecrDb();
        getContentPane().setBackground(new Color(255, 204, 204));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel7 = new javax.swing.JLabel();
        name = new javax.swing.JTextField();
        Aadharno = new javax.swing.JTextField();
        drunkist = new javax.swing.JRadioButton();
        drunkist2 = new javax.swing.JRadioButton();
        gender = new javax.swing.JRadioButton();
        gender2 = new javax.swing.JRadioButton();
        submit = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        BG = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        CD = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TA = new javax.swing.JTextArea();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        getContentPane().add(name);
        name.setBounds(270, 40, 180, 30);

        Aadharno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AadharnoActionPerformed(evt);
            }
        });
        getContentPane().add(Aadharno);
        Aadharno.setBounds(270, 100, 180, 30);

        drunkist.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        drunkist.setText("Yes");
        getContentPane().add(drunkist);
        drunkist.setBounds(270, 170, 60, 25);

        drunkist2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        drunkist2.setText("No");
        drunkist2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drunkist2ActionPerformed(evt);
            }
        });
        getContentPane().add(drunkist2);
        drunkist2.setBounds(370, 170, 60, 25);

        gender.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        gender.setText("Male");
        getContentPane().add(gender);
        gender.setBounds(260, 220, 70, 25);

        gender2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        gender2.setText("Female");
        gender2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gender2ActionPerformed(evt);
            }
        });
        getContentPane().add(gender2);
        gender2.setBounds(360, 220, 80, 25);

        submit.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        submit.setText("Submit");
        submit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitActionPerformed(evt);
            }
        });
        getContentPane().add(submit);
        submit.setBounds(160, 440, 100, 25);

        jLabel1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel1.setText("Name");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(130, 40, 70, 17);
        getContentPane().add(jLabel3);
        jLabel3.setBounds(211, 138, 0, 0);

        jLabel5.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel5.setText("Alcoholist");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(120, 170, 90, 20);

        jLabel6.setFont(new java.awt.Font("Lucida Calligraphy", 1, 11)); // NOI18N
        jLabel6.setText("Gender");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(125, 220, 50, 20);
        getContentPane().add(BG);
        BG.setBounds(270, 250, 200, 30);

        jLabel17.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel17.setText("Contact details");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(110, 290, 120, 17);

        jLabel8.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel8.setText(" BloodGroup");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(110, 260, 100, 17);

        CD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CDActionPerformed(evt);
            }
        });
        getContentPane().add(CD);
        CD.setBounds(270, 290, 200, 30);

        jLabel9.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel9.setText("Address");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(120, 354, 60, 20);

        TA.setColumns(20);
        TA.setRows(5);
        jScrollPane1.setViewportView(TA);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(270, 330, 200, 96);

        jButton1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jButton1.setText("Cancel");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(310, 440, 90, 25);

        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 12)); // NOI18N
        jLabel2.setText("Aadhar no");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(120, 104, 100, 20);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void submitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitActionPerformed
        // TODO add your handling code here:
        try
      {      
      Statement st = conn.createStatement();
      String nameg=name.getText();
     
      String Aadhar=Aadharno.getText();
      String blood=BG.getText();
      String contact=CD.getText();
      String addr=TA.getText();
      
      String d="";
      String g="";
           

      if(drunkist.isSelected()){
          d=drunkist.getText();
      }
      if(drunkist2.isSelected()){
          d=drunkist2.getText();
      }
      if(gender.isSelected()){
          g=gender.getText();
      }
      if(gender2.isSelected()){
          g=gender2.getText();
      }
        
           if(nameg.equals("") || Aadhar.equals("") || blood.equals("") || contact.equals("") || addr.equals("")|| d.equals("")|| g.equals("")){
               JOptionPane.showMessageDialog(null,"Please Enter All the Details");
           }
            else{
               if(d.equals("No")){
                if(contact.length()==10 && Aadhar.length()==12){
                    String sql = "SELECT Contactdetails FROM vis WHERE Contactdetails='"+contact+"'";
                    PST=conn.prepareStatement(sql);
                   RS=PST.executeQuery();
                
                       if(RS.next()){
                        JOptionPane.showMessageDialog(null,"You Have Already Registered..!!");
                
                        }
      
                       else{    
      
      st.executeUpdate("INSERT INTO vis VALUES ('"+nameg+"','"+Aadhar+"','"+d+"','"+g+"','"+blood+"','"+contact+"','"+addr+"')");
      JOptionPane.showMessageDialog(null,"Your details are included in the donor list successfully!!");
                       }}
                else{
                    JOptionPane.showMessageDialog(null,"Plese check your mobile number and aadhar number");  
                }
               }
               else{
                 JOptionPane.showMessageDialog(null,"You are not Eligible to donate blood");  
               }}
               
           }
    catch (Exception e)
    {
      //JOptionPane.showMessageDialog(e.getMessage());
                  System.err.println(e.getMessage());

    }
    }//GEN-LAST:event_submitActionPerformed

    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed

    private void drunkist2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drunkist2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drunkist2ActionPerformed

    private void gender2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gender2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_gender2ActionPerformed

    private void CDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CDActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
new homee ().setVisible(true);
      this.setVisible(false);         // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void AadharnoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AadharnoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_AadharnoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(v1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new v1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Aadharno;
    private javax.swing.JTextField BG;
    private javax.swing.JTextField CD;
    private javax.swing.JTextArea TA;
    private javax.swing.JRadioButton drunkist;
    private javax.swing.JRadioButton drunkist2;
    private javax.swing.JRadioButton gender;
    private javax.swing.JRadioButton gender2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField name;
    private javax.swing.JButton submit;
    // End of variables declaration//GEN-END:variables
}
